# Generated by Django 2.2.1 on 2019-05-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
    ]
