# Generated by Django 2.2.1 on 2019-05-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190511_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_date'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
    ]
