# Generated by Django 2.2.1 on 2019-05-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='institute/', verbose_name='Imagem 1')),
                ('image2', models.ImageField(null=True, upload_to='institute/', verbose_name='Imagem 2')),
                ('image3', models.ImageField(null=True, upload_to='institute/', verbose_name='Imagem 3')),
                ('aboutInstitute', models.TextField(max_length=520, verbose_name='Sobre o Instituto')),
                ('FraseInstitute', models.TextField(max_length=120, verbose_name='Frase Institucional')),
                ('AutorInstitute', models.CharField(max_length=30, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Sobre o instituto',
                'verbose_name_plural': 'Sobre o instituto',
            },
        ),
    ]
