# Generated by Django 2.2.1 on 2019-05-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_auto_20190517_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucional',
            options={'verbose_name': 'Sobre o Citi', 'verbose_name_plural': 'Sobre o CITi'},
        ),
        migrations.AlterField(
            model_name='institucional',
            name='aboutInstitute',
            field=models.TextField(max_length=520, verbose_name='Sobre o CITi'),
        ),
    ]
